## Data Science Basic

Data Science is basically use of data and machine learning algorithms to make prediction<br/>
and take out insight from the data.

There are two types of predictions in Data Science.

**Classification**: to find out in which class the entity belongs.
for ex if we are given various variable of flower like length of petals<br/>
width of petal and color then find the flower.

**Regression**: in regression we need to find the output value of based on other variable.<br/>
for example if we are given variables of house like no. of bedrooms , size of rooms etc<br/>
then predict price of house.

## Data science steps

There are 8 basic steps in datascience and there are libraries to help us with each step.

1. Data loading:- to load the data.
2. Data Cleaning:- to deal with missing data
3. Data Normalizing:- this we will study later
4. Train test split:- to keep some data aside for testing
5. making machine learning model:- using ML algoritm to train
6. making prediction:- making prediction on test data
7. calculating accuracy:- testing how well our data can predict
8. feature engineering:- deciding which columns to keep 
   to increase performance.


## Libraries for DataScience

There are four basic libraries which will help us to perform above steps.

1. numpy
2. pandas
3. matplotlib
5. scikit learn

**numpy** : is used to perform basic array and matrix calculation.<br/>
as there are no array in python numpy was created, which is faster than<br/>
list in python. all the libraries pandas, matplotlib and scikitlearn are<br/>
based on numpy all of them use numpy internally. so we might rarely use numpy<br/>
library directly.

**pandas**: This is very important library. data loading and manipulation is done using<br/>
pandas. Pandas take a file and convert it to rows and columns like object and this object<br/>
is called DataFrame in pandas and each column is called Series.

**matplotlib**: This is another numpy based library which is used to make plot of graphs like.<br/>
barplot, countplot, scatterplot,etc.

**scikit-learn**: This library includes most of the machine learning algorithms which we are going<br/>
use.

Basic thing that you have to keep in mind is Data Science is about making correct prediction<br/>
we do not need detailed understanding of all the agorithm to make model only abstract understanding<br/>
of how algorithm works is enough.



**BASIC MACHINE LEARNINNG ALGORITHMS**


1. Linear Regression
2. Logistic Regression
3. Decision Tree
4. SVM
5. Naive Bayes
6. kNN
7. K-Means
8. Random Forest
9. Dimensionality Reduction Algorithms
10. Gradient Boosting algorithms
     GBM
     XGBoost
     LightGBM
     CatBoost
     
This are all machine-learning algorithms which are used in machine learning.



## Let's Make basic model

In [1]:
#importing libraries

import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt

#we are writing as then shorthand for library so we do not have
#to use full name while accesing libraries.

# if you don't have this libraries use
# pip install library_name
# to run jupyter notebook block press "shift + enter"

we are going to use iris dataset for basic tutorial<br/>
this is considerd as Hello World of data science<br/>
here task is to predict the type of iris flower based on petal_length and width<br/>
and sepal_length and width.
 
download the dataset from [here](https://www.kaggle.com/uciml/iris)<br/>
if you don't have kaggle account then make one.

In [2]:
# after downloading data place it in same folder as notebook
# and extract it you will get iris.csv file

#now we will load this file as Pandas DataFrame()

data = pd.read_csv("iris.csv")

In [5]:
#to look at first five rows of data use DataFrame.head()
# if we want to look at more rows use head(number)
data.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [6]:
#to look at last five rows of data
# if we want to look at more rows use tail(number)
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [7]:
# to access specific column of DataFrame use DataFrame["column_name"]
data["SepalLengthCm"].head()

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: SepalLengthCm, dtype: float64

In [8]:
# for accessing more than one column use DataFrame[["list of columns"]]
data[["SepalLengthCm","SepalWidthCm"]].head()

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6

In [10]:
type(data)
# as you can see type of data is pandas DataFrame

pandas.core.frame.DataFrame

In [12]:
type(data["SepalLengthCm"])
# and type of each column is Series

pandas.core.series.Series

In [14]:
#to get number of rows and columns
data.shape
# here it return python tuple which is like (rows,column)
#remember data.shape is not function so don't write data.shape()
#with brackets.

(150, 6)

In [16]:
#to get basic info lie mean, median and standard deviation
# use DataFrame.describe()
data.describe()
#it gives basic info of each column

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [17]:
# to get the data type of each columns use .info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


Now we will learn about two main function of pandas DataFrame<br/>
loc and iloc. which allows us to access specific rows and columns<br/> 
in data

The format of iloc is data.iloc[list of rows,list of columns]

In [18]:
#get 1st row and 2nd column
data.iloc[0,1]
#like python in pandas row and cols starts at 0.

5.1

In [19]:
#get 1st and 6th row and 2nd column
data.iloc[[0,5],1]

0    5.1
5    5.4
Name: SepalLengthCm, dtype: float64

In [20]:
#one imip feature of iloc is ":" symbol it means all of rows or columns
data.iloc[:,3]
#get all the rows and 4th column

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: PetalLengthCm, Length: 150, dtype: float64

In [21]:
data.iloc[2,:]
#get 3rd row and all the columns

Id                         3
SepalLengthCm            4.7
SepalWidthCm             3.2
PetalLengthCm            1.3
PetalWidthCm             0.2
Species          Iris-setosa
Name: 2, dtype: object

In [23]:
# to get all the rows or from a to b use a:b+1
data.iloc[1:5,3]
# remember iloc will not consider last value
# as in above case we will get rows 1,2,3,4 but not 5

1    1.4
2    1.3
3    1.5
4    1.4
Name: PetalLengthCm, dtype: float64

In [26]:
data.iloc[0:5,0:3]
#get first five rows and first 3 columns

Id  SepalLengthCm  SepalWidthCm
0   1            5.1           3.5
1   2            4.9           3.0
2   3            4.7           3.2
3   4            4.6           3.1
4   5            5.0           3.6

In [27]:
# if you need first n columns or row 
# you can ignore writing 0 in a:b for ex
data.iloc[:5,:]
#first five rows and all columns


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Now difference between iloc and loc is that<br/>
loc allow us to use column names to access columns<br/>


In [28]:
data.loc[:5,"SepalLengthCm"]
#get 5 rows and SepalLengthCm column


0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
5    5.4
Name: SepalLengthCm, dtype: float64

In [29]:
data.loc[:5,["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
#get 5 rows and "SepalWidthCm","PetalLengthCm","PetalWidthCm" column

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2
5            5.4           3.9            1.7           0.4

In [31]:
# if you use column names in iloc you will get error
data.iloc[:5,["SepalLengthCm"]]


IndexError: .iloc requires numeric indexers, got ['SepalLengthCm']

In [32]:
#to get all the column names
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

As you can see that here data.columns return an array the column names<br/>
but here the type of the array is Index which is another object like<br/>
DataFrame and Series in pandas which is only used for column names and Index<br/>
of data so nothing new there

pandas use numpy as internal library let's see how.

Pandas DataFrame is made of two things index and values<br/>


In [33]:
data.index

RangeIndex(start=0, stop=150, step=1)

In [34]:
data.values

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
 

As you can see data.values gives us matrix like arrangement rather<br/>
then proper row column arrangement which we see in DataFrame.


In [35]:
type(data.values)

numpy.ndarray

As you can see that type of data.values give numpy array

This were the basic function of pandas library. There are thousands of<br/>
function in pandas but we do not need to know every function as that's<br/>
too much hard work so we will learn each function as we need

To look at all the function pandas provide look pandas official documentation [here](https://pandas.pydata.org/docs/reference/index.html)

## Data Cleaning

Data cleaning is the process where we deal with missing values<br/>
and preapre out data for fitting in to model

To calculate the missing value pandas has function called DataFrame.isnull()
this will not return count of null values but only boolean matrix for ex

In [37]:
data.iloc[:5,:].isnull()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0  False          False         False          False         False    False
1  False          False         False          False         False    False
2  False          False         False          False         False    False
3  False          False         False          False         False    False
4  False          False         False          False         False    False

as you can see it will check if the value is null or not and return true if it's null and false if it's not

**NOTE** : what is null values? how to pandas know that a value is null value?<br/>
Important thing to note is numpy has a value which is considered as null value<br/>
we can access that value as np.nan. pandas will look for np.nan value in the data.

Let us create an exaple dataframe to understand

In [39]:
# If can create our own DataFrame if we don't have a csv file 
# by using python dictionary and pd.DataFrame() function like

#key of dict1 is column
# and values are rows
dict1 = {"column1":[1,2,3,4,5],
         "column2":[2,3,4,np.nan,7],
         "column3":["hello",np.nan,"world","null",np.nan]}

#pass dict1 as argument in pa.DataFrame() function
temp = pd.DataFrame(dict1)

#first five rows of dataframe
temp.head()

column1  column2 column3
0        1      2.0   hello
1        2      3.0     NaN
2        3      4.0   world
3        4      NaN    null
4        5      7.0     NaN

All np.nan values are represented as NaN in DataFrame
Now let's apply .isnull() function to DataFrame

In [40]:
temp.isnull()

column1  column2  column3
0    False    False    False
1    False    False     True
2    False    False    False
3    False     True    False
4    False    False     True

All the np.nan values are marked as True.<br/>
in column three we have written a string "null"<br/>
but pandas will not understand it as null because we <br/>
have written null it will consider it as string.

To get total null values in all columns use .sum() function

In [41]:
temp.isnull().sum()

column1    0
column2    1
column3    2
dtype: int64

In [42]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

Here there are no null values in DataFrame.<br/>
What if there were null values.<br/>

There are two main ways to deal with NaN values either delete it<br/>
or replace the NaN values with mean value in columns

## train test split

Now we will split the data in training and testing<br/>
we will use scikit-learn library for this.

In [43]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [49]:
#sklearn has model_selection class which has function train_test_split
from sklearn.model_selection import train_test_split

#get all the columns except Species type as X
# we do not need id as it is not used in determing species of flower
X = data.loc[:,["SepalLengthCm" ,"SepalWidthCm","PetalLengthCm","PetalWidthCm"]].values
y = data.loc[:,"Species"].values

#train_test_split will return four values train_X,train_y,test_X,test_y
# it will take features X and label y as argument along with portion of 
# data to be kept for testing like 

train_X,test_X,train_y,test_y = train_test_split(X,y,test_size=0.2)

#20% data for testing

## Label encoder

As Species column of the data is string it can not be used to <br/>
make model we have to convert it to numbers. <br/>


In [50]:
# Let's find out how many types of Species are there
# for that we will use DataFrame.unique() function which
# will give unique values in column

data["Species"].unique()
# we can use .nunique() just to get number

#there are three types of iris flower
#we need to convert this flower names to number 
#like 0,1,2 for each flower

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [51]:
# for converting it to number we will use LabelEncoder class of sklearn
from sklearn.preprocessing import LabelEncoder

#first make an object of LabelEncoder
l = LabelEncoder()

#now we will fit this label encoder to data
# fit function will just figure out what number we
# have to apply but will not convert the species to number
# for that we have to use transform function of LabelEncoder class

#we have to fit and transform the train data so use fit_transform
train_y = l.fit_transform(train_y)

#we just need to transform test data
test_y = l.transform(test_y)

In [53]:
train_y
# flowers are converted to number

array([1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 1, 2, 0, 1, 2, 1, 1, 0, 1, 2, 1,
       2, 1, 2, 0, 1, 2, 2, 1, 2, 2, 0, 1, 0, 0, 2, 0, 1, 2, 2, 0, 2, 0,
       0, 2, 1, 2, 1, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0,
       1, 1, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 1, 2, 2, 1, 1, 1, 2, 1,
       2, 0, 1, 0, 2, 0, 0, 1, 0, 2])

## Making Model

we will use sklearn library for making models

1. Linear Regression
2. Logistic Regression
3. Decision Tree
4. SVM
5. Naive Bayes
6. kNN
7. K-Means
8. Random Forest
9. Gradient Boosting algorithms
     GBM
     XGBoost
     LightGBM
     CatBoost

Linear Regression ,Logistic Regression, are only regression model so can not be used<br/>
for classification and all other models could be used for classification and regression


## 3. Decision Tree

To know what decision tree is see [this](https://www.youtube.com/watch?v=7VeUPuFGJHk) video

In [55]:
#import DecisionTreeClassifier form sklearn library
from sklearn.tree import DecisionTreeClassifier

#make an object of DecisionTreeClassifier class

model1 = DecisionTreeClassifier()

#now train the data using fit method
model1.fit(train_X,train_y)

#predict on test data using prediction method
prediction = model1.predict(test_X)

In [56]:
prediction

array([2, 2, 2, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 0, 2,
       0, 0, 0, 1, 1, 0, 0, 1])

In [57]:
test_y

array([2, 2, 2, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 0, 2,
       0, 0, 0, 1, 1, 0, 0, 1])

In [59]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,prediction)

#confusion matrix shows how many entity are in their own class
# and how many are not 
# all the 0 shows that there is no flower which is predicted in  wrong class
# usually you won't see 100% accuracy in models

array([[13,  0,  0],
       [ 0,  9,  0],
       [ 0,  0,  8]], dtype=int64)

As accuracy is 100% feature engineering is not required.

## 4. SVM (support vector machine) classifier 

how svm works [here](https://www.youtube.com/watch?v=efR1C6CvhmE)

In [60]:
from sklearn.svm import SVC


#make an object of SVC class
model2 = SVC()

#now train the data using fit method
model2.fit(train_X,train_y)

#predict on test data using prediction method
prediction = model2.predict(test_X)

confusion_matrix(test_y,prediction)

C:\Users\Maunish Dave\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([[13,  0,  0],
       [ 0,  9,  0],
       [ 0,  0,  8]], dtype=int64)

# 5. K-NN (k nearest neighbors  classifer)

for knn tutorial [here](https://www.youtube.com/watch?v=HVXime0nQeI)

In [61]:
from sklearn.neighbors import KNeighborsClassifier

#make an object of KNeighborsClassifier class
model3 = KNeighborsClassifier(n_neighbors=5)

#now train the data using fit method
model3.fit(train_X,train_y)

#predict on test data using prediction method
prediction = model3.predict(test_X)

confusion_matrix(test_y,prediction)

array([[13,  0,  0],
       [ 0,  9,  0],
       [ 0,  0,  8]], dtype=int64)

**Try to apply all other algorithm except <br/>
gradient boosting algoritms they are different**