In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]
a + b
output = list()

In [3]:
for i,j in zip(a,b):
    output.append(i+j)

In [4]:
output

[2, 4, 6, 8, 10]

In [5]:
g_array = np.array(a)

In [6]:
g_array.sum()

15

In [7]:
a =np.array([1,2,3,4,5])
b = np.array([11,12,13,14,15])

a + b

array([12, 14, 16, 18, 20])

In [8]:
a * b

array([11, 24, 39, 56, 75])

In [9]:
a / b

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333])

In [10]:
a - b

array([-10, -10, -10, -10, -10])

In [11]:
type(a)  

numpy.ndarray

In [12]:
a.dtype

dtype('int32')

In [13]:
a.__array_interface__

{'data': (2058904322736, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (5,),
 'version': 3}

In [14]:
a.shape

(5,)

In [15]:
print(np.sin(a))
print(np.sqrt(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [16]:
sum

<function sum(iterable, start=0, /)>

In [17]:
np.sum

<function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)>

# selecting arry elements

In [18]:
a[0]

1

In [19]:
a[0] = 10

In [20]:
a

array([10,  2,  3,  4,  5])

In [116]:
a[0] = 10.8  #numpy will automatically truncat the number to corresponding dtype

In [22]:
a

array([10,  2,  3,  4,  5])

In [23]:
a = np.array([1,2,3,4,5.7])  #numpy will automatically determine the type of the array

In [24]:
a.dtype

dtype('float64')

In [25]:
a = np.array([1,2,3,4,5,5.0],dtype='int32')

In [26]:
a.dtype

dtype('int32')

In [27]:
c = np.array([[1,2,3],[2,3,4],[11,12,13]])


In [28]:
c

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [11, 12, 13]])

In [29]:
c.dtype

dtype('int32')

In [30]:
c.shape

(3, 3)

In [31]:
a

array([1, 2, 3, 4, 5, 5])

In [32]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [5]])

In [33]:
a.reshape(1,-1)  #converts the column to row matrix

array([[1, 2, 3, 4, 5, 5]])

In [34]:
a.reshape(-1,1)  #converts row to column matrix

array([[1],
       [2],
       [3],
       [4],
       [5],
       [5]])

In [35]:
c

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [11, 12, 13]])

In [36]:
c.size  #total number of elments

9

In [37]:
c.nbytes

36

In [38]:
c[0,0]

1

In [39]:
c[0] #give all ohter dimension

array([1, 2, 3])

# slicing

In [40]:
a = np.array([10,11,12,13,14])


In [41]:
a[1:3]

array([11, 12])

In [42]:
a[1:-2]

array([11, 12])

In [43]:
a[:3]

array([10, 11, 12])

In [44]:
a[-2:]  #last two elements of array

array([13, 14])

In [45]:
a[::2]

array([10, 12, 14])

In [46]:
a = np.arange(25).reshape((5,5))

In [47]:
a[0,3:5]

array([3, 4])

In [48]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
a[-2:,-2:]

array([[18, 19],
       [23, 24]])

In [50]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [51]:
a[2::2,::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [52]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [53]:
a[1::2,:-1:2]

array([[ 5,  7],
       [15, 17]])

In [54]:
a[-1,:]

array([20, 21, 22, 23, 24])

# Fancy indexing


In [55]:
a = np.arange(0,80,10)

In [56]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [57]:
index = [0,1,-3]
a[index]

array([ 0, 10, 50])

In [58]:
index =  np.array([1,0,0,0,1,1,1,0],dtype='bool')
a[index]

array([ 0, 40, 50, 60])

In [59]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [60]:
index = a < 30
a[index]

array([ 0, 10, 20])

In [61]:
a[a<30] =100

In [62]:
a

array([100, 100, 100,  30,  40,  50,  60,  70])

In [63]:
(a < 40).any() #will return true if any of the value will return required conditon

True

In [64]:
(a<= 100).all() #will return true if all the elements will follow the condition

True

In [65]:
(a > 30) & (a < 40) #bitwise operator

array([False, False, False, False, False, False, False, False])

In [66]:
a.view()

array([100, 100, 100,  30,  40,  50,  60,  70])

In [67]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [68]:
a = np.array([[1.2,3.4,4.5],[1.0,2.0,3.0]],dtype='float32')
a.ravel()

array([1.2, 3.4, 4.5, 1. , 2. , 3. ], dtype=float32)

In [69]:
g = np.arange(25).reshape((5,5))

In [70]:
mask = (g % 3 ==0)

In [71]:
mask

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [72]:
g[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [73]:
g[g%3 != 0] = 0

In [74]:
g

array([[ 0,  0,  0,  3,  0],
       [ 0,  6,  0,  0,  9],
       [ 0,  0, 12,  0,  0],
       [15,  0,  0, 18,  0],
       [ 0, 21,  0,  0, 24]])

In [75]:
output = np.empty_like(g)

In [76]:
output.fill(np.nan)

In [77]:
output

array([[-2147483648, -2147483648, -2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648, -2147483648]])

In [78]:
mask = (g%3 == 0)
output[mask] = g[mask]

In [79]:
output

array([[ 0,  0,  0,  3,  0],
       [ 0,  6,  0,  0,  9],
       [ 0,  0, 12,  0,  0],
       [15,  0,  0, 18,  0],
       [ 0, 21,  0,  0, 24]])

In [80]:
np.where(g%3 ==0, g,np.nan)

array([[ 0.,  0.,  0.,  3.,  0.],
       [ 0.,  6.,  0.,  0.,  9.],
       [ 0.,  0., 12.,  0.,  0.],
       [15.,  0.,  0., 18.,  0.],
       [ 0., 21.,  0.,  0., 24.]])

## computing with arrays

rule1: operation between multiple array object are first checked for proper shape match.

rule2: Mathematical operators (+,-,*,/,exp,log) apply element by element , on the values

rule3: Reduction operations (mean, std, skew kurt,sum, prod,) apply to the whole array, unless an axis is specified.

rule4 : Missiong values propagate unless explicitly ignored (nanmean, nansum, ).



In [82]:
a = np.ones((3,2))
b = np.ones((2,))

In [86]:
print("a ",a)
print("b ",b)

a + b

a  [[1. 1.]
 [1. 1.]
 [1. 1.]]
b  [1. 1.]


array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [88]:
np.mean(a+b)

2.0

if we add anything to nan result will be nan

In [89]:
np.nan + 8

nan

In [90]:
b = np.array([1,np.nan,0])
np.sum(b)

nan

In [94]:
a.min()

1.0

In [95]:
a.argmin() #gives position of the minimum value

0

In [96]:
b.argmin()  

1

In [97]:
a = np.arange(-15,15).reshape(5,6) ** 2

In [100]:
np.mean(a,axis=1)

array([159.16666667,  45.16666667,   3.16666667,  33.16666667,
       135.16666667])

In [101]:
np.mean(a,axis=0)

array([81., 76., 73., 72., 73., 76.])

In [105]:
np.min(a)

0

In [110]:
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [111]:
a.argmin()

15

In [114]:
a.min(axis=1).argmin()

2

In [115]:
a.min(axis=0).argmin()

3