In [12]:
import numpy as np
import sys
import time

In [17]:
#size of the list vs array
a = range(1000)
b = np.arange(1000)

print("a:",sys.getsizeof(5) * len(a))
print("b:" ,b.size*b.itemsize)

a: 28000
b: 4000


In [20]:
#comparing time of adding list vs array
list1 = range(1000000)
array = np.arange(1000000)

start = time.time()
result = [(x+y) for x,y in zip(list1,list1)]
end = time.time()

print("time taken by list ",(end -start)*1000)

start = time.time()
result = array + array
end = time.time()

print("time taken by array ",(end - start)*1000)


time taken by list  197.82257080078125
time taken by array  27.71306037902832


In [21]:
#multidimensional list
a = np.array([1,2,3,4,5])
a.ndim

1

In [22]:
a.dtype

dtype('int32')

In [24]:
a = np.array([[1,2],[1,2],[3,4]])
a.shape

(3, 2)

In [25]:
a.size #number of element in array

6

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
c =np.ones((3,5))

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [34]:
b =np.linspace(1,5,10)

In [35]:
b.ravel()

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [38]:
c.ravel() #it will not affect the array it will return new array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
c.min()

1.0

In [40]:
c.max()

1.0

In [41]:
a.sum()

13

In [42]:
np.sqrt(c)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.std(a)

1.0671873729054748

In [50]:
#numpy sclicing and indexing
a= np.array([6,7,8])
a[0:2]

array([6, 7])

In [51]:
c = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [52]:
c[1,2]

3

In [54]:
c[0:2,2]

array([8, 3])

In [55]:
a[-1]

8

In [57]:
c[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [58]:
#how to iterate through array
for row in c:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [60]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [62]:
a, b

(array([[0, 1],
        [2, 3],
        [4, 5]]), array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [63]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [64]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [65]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [67]:
result = np.hsplit(a,3)

In [68]:
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [69]:
b =  a> 4

In [70]:
b

array([[False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [71]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
import numpy as np

a = np.arange(25).reshape((5,5))
b = np.arange(75).reshape((5,5,3))
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]


In [5]:
c = a[:,:,np.newaxis] + b
print(c)

[[[ 0  1  2]
  [ 4  5  6]
  [ 8  9 10]
  [12 13 14]
  [16 17 18]]

 [[20 21 22]
  [24 25 26]
  [28 29 30]
  [32 33 34]
  [36 37 38]]

 [[40 41 42]
  [44 45 46]
  [48 49 50]
  [52 53 54]
  [56 57 58]]

 [[60 61 62]
  [64 65 66]
  [68 69 70]
  [72 73 74]
  [76 77 78]]

 [[80 81 82]
  [84 85 86]
  [88 89 90]
  [92 93 94]
  [96 97 98]]]


In [6]:
c[::1,[1,-1]]

array([[[ 4,  5,  6],
        [16, 17, 18]],

       [[24, 25, 26],
        [36, 37, 38]],

       [[44, 45, 46],
        [56, 57, 58]],

       [[64, 65, 66],
        [76, 77, 78]],

       [[84, 85, 86],
        [96, 97, 98]]])

In [1]:
import numpy as np
a = np.arange(25).reshape((5,5))


In [6]:
a = np.arange(10)
print(a)
print(a.strides)

[0 1 2 3 4 5 6 7 8 9]
(4,)


In [15]:
w = 5
x = np.lib.stride_tricks.as_strided(a,shape=(len(a) - w + 1,w),strides=a.strides *2 )
print(x)
#no new memory created in this method all is done using refrence

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [18]:
z = np.array([np.sum(i) for i in x])

In [19]:
print(z)

[10 15 20 25 30 35]


In [20]:
np.sum(x)

135

In [21]:
np.sum(x[0])

10

In [26]:
%time z = np.array([np.sum(x[i]) for i in range(len(x))])

Wall time: 0 ns


In [27]:
z

array([10, 15, 20, 25, 30, 35])

In [34]:
a = np.arange(25).reshape((5,5))

In [35]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [36]:
a.shape[:-1]

(5,)

In [39]:
a.__array_interface__

{'data': (2848094701632, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (5, 5),
 'version': 3}

## Einsum

In [40]:
a = np.arange(9).reshape((3,3))
b = np.arange(9,18).reshape((3,3))

In [42]:
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [43]:
np.einsum("ij -> ij",a)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.einsum("ij -> i",a)

array([ 3, 12, 21])

In [45]:
np.einsum("ii -> i",a)

array([0, 4, 8])

In [48]:
np.einsum("jj -> j",a)

array([0, 4, 8])

In [49]:
np.einsum("ii ->",a)

12

In [50]:
np.einsum("ij,ij -> ij",a,b)

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [52]:
a * b

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [53]:
np.einsum("ij,jk -> ik",a,b)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [55]:
a @ b   #traditional multiplication of matrix

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [58]:
matrix = np.arange(25).reshape((5,5))
submatrix = np.array([[1,3,4],
                     [3,4,5],
                     [5,6,7]])

In [59]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
matrix_shape = matrix.shape
submatrix_shape = submatrix.shape

In [62]:
conv_shape = tuple(np.subtract(matrix.shape ,submatrix_shape) + 1) + submatrix_shape

In [63]:
conv_shape

(3, 3, 3, 3)

In [64]:
conv_strides = matrix.strides * 2

In [65]:
conv_strides

(20, 4, 20, 4)

In [66]:
sub_matrix = np.lib.stride_tricks.as_strided(matrix,shape=conv_shape,strides = conv_strides)

In [67]:
sub_matrix

array([[[[ 0,  1,  2],
         [ 5,  6,  7],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 6,  7,  8],
         [11, 12, 13]],

        [[ 2,  3,  4],
         [ 7,  8,  9],
         [12, 13, 14]]],


       [[[ 5,  6,  7],
         [10, 11, 12],
         [15, 16, 17]],

        [[ 6,  7,  8],
         [11, 12, 13],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [12, 13, 14],
         [17, 18, 19]]],


       [[[10, 11, 12],
         [15, 16, 17],
         [20, 21, 22]],

        [[11, 12, 13],
         [16, 17, 18],
         [21, 22, 23]],

        [[12, 13, 14],
         [17, 18, 19],
         [22, 23, 24]]]])

In [70]:
convouled = np.einsum("ij, ijkl -> kl",submatrix,sub_matrix)

In [71]:
convouled

array([[285, 323, 361],
       [475, 513, 551],
       [665, 703, 741]])