## Importing libraries for CNN

In [58]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense , Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
import itertools



In [20]:
train_path = "train"
test_path = "test"
valid_path ="valid"

In [31]:
train_batches = ImageDataGenerator().flow_from_directory(train_path,target_size=(224,224),classes=['cats','dogs'],batch_size=10)
valid_batches = ImageDataGenerator().flow_from_directory(valid_path,target_size=(224,224),classes=['cats','dogs'],batch_size=4)
test_batches = ImageDataGenerator().flow_from_directory(test_path,target_size=(224,224),classes=['cats','dogs'],batch_size=10)

Found 200 images belonging to 2 classes.
Found 40 images belonging to 2 classes.
Found 40 images belonging to 2 classes.


In [68]:
_, train_labels = next(train_batches)
train_labels

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [69]:
model = Sequential()
model.add(Conv2D(32,(3,3),input_shape=(224,224,3),activation='relu'))

model.add(Flatten())
model.add(Dense(2,activation='softmax'))


In [70]:
model.compile(Adam(lr = .0001),loss='categorical_crossentropy',metrics=['accuracy'])


In [71]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 222, 222, 32)      896       
_________________________________________________________________
flatten_3 (Flatten)          (None, 1577088)           0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 3154178   
Total params: 3,155,074
Trainable params: 3,155,074
Non-trainable params: 0
_________________________________________________________________


In [72]:
model.fit_generator(train_batches,steps_per_epoch=20,validation_data = valid_batches,validation_steps=4,epochs = 5,verbose=2)

Epoch 1/5
 - 8s - loss: 7.8942 - acc: 0.5100 - val_loss: 7.0517 - val_acc: 0.5625
Epoch 2/5
 - 6s - loss: 7.7367 - acc: 0.5200 - val_loss: 11.0812 - val_acc: 0.3125
Epoch 3/5
 - 6s - loss: 8.3008 - acc: 0.4850 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 4/5
 - 6s - loss: 8.2202 - acc: 0.4900 - val_loss: 7.0517 - val_acc: 0.5625
Epoch 5/5
 - 6s - loss: 7.5755 - acc: 0.5300 - val_loss: 9.0664 - val_acc: 0.4375


## Predicting using keras

In [73]:
test_img, test_labels = next(test_batches)

In [74]:
test_labels

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [75]:
test_labels = test_labels[:,0]

In [76]:
predection = model.predict_generator(test_batches,steps = 1,verbose=0)
predection

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [77]:
from sklearn.metrics import confusion_matrix

In [78]:
confusion_matrix(test_labels,predection[:,0])

array([[4, 0],
       [6, 0]], dtype=int64)

# cnn practise

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers.core import Dense, Flatten
from keras.layers import Activation  # layers contains all Activation function like relu, softmax,sigmoid, hard_sigmoid,
                      `               # to use advanced activation functions like PRelu or LeakyRelu us advanced_activaions insteas of Activation
from keras.optimizers import Adam     # it contains optimizers like adam , SGD(stocastic gradient descent) etc..
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
import itertools

In [25]:
from keras.layers import MaxPooling2D
from keras import optimizers

In [4]:
train_path = "train"
test_path = "test"
valid_path = "valid"

In [50]:
train_batch = ImageDataGenerator().flow_from_directory(train_path,target_size=(240,240),batch_size=10,classes=['cats','dogs'])
test_batch = ImageDataGenerator().flow_from_directory(test_path,target_size=(240,240),batch_size=10,classes=['cats','dogs'])
valid_batch = ImageDataGenerator().flow_from_directory(valid_path,target_size=(240,240),batch_size=10,classes=['cats','dogs'])

Found 200 images belonging to 2 classes.
Found 40 images belonging to 2 classes.
Found 40 images belonging to 2 classes.


## defining model

we will make a neruatl networks with 1 block which contains following things.

conv2d(32)

MaxPolling2d(2,2) 

Flatten()
 
so after flattening the data we can use Dense layer

so we will use 128 filters for flatten data 



In [55]:
def define_model():
    model = Sequential()
    model.add(Conv2D(32,kernel_size= (3,3),activation='relu',input_shape=(240,240,3),kernel_initializer="he_uniform",padding="same"))
    model.add(MaxPooling2D(2,2))
    model.add(Flatten())
    model.add(Dense(128,activation='relu',kernel_initializer="he_uniform"))
    model.add(Dense(2,activation="sigmoid"))
    
    opt = optimizers.SGD(lr=0.01,momentum=0.9)
    model.compile(optimizer=opt,loss='categorical_crossentropy',metrics = ['accuracy'])
    return model

In [56]:
model = define_model()

In [57]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_11 (Conv2D)           (None, 240, 240, 32)      896       
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 120, 120, 32)      0         
_________________________________________________________________
flatten_10 (Flatten)         (None, 460800)            0         
_________________________________________________________________
dense_19 (Dense)             (None, 128)               58982528  
_________________________________________________________________
dense_20 (Dense)             (None, 2)                 258       
Total params: 58,983,682
Trainable params: 58,983,682
Non-trainable params: 0
_________________________________________________________________


In [74]:
model.fit_generator(train_batch,steps_per_epoch = len(test_batch),validation_data = valid_batch,validation_steps = len(valid_batch),epochs = 20,verbose = 0)

In [65]:
predict  = model.predict_generator(test_batch,steps = 1, verbose = 0)

In [63]:

_, acc = model.evaluate_generator(test_batch, steps=len(test_batch), verbose=0)
print('> %.3f' % (acc * 100.0))

> 52.500


In [69]:
test_image, test_labels= next(test_batch)

In [73]:
confusion_matrix(test_labels[:,0],predict[:,0])

array([[6, 0],
       [4, 0]], dtype=int64)